services:
  app:
    build: .
    container_name: yatc-app
    ports:
      - '3000:3000'
    environment:
      # Usando variáveis de ambiente diretamente - funcionam em qualquer ambiente
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
